# Generated by Django 5.1.6 on 2025-02-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(default='oie'),
            preserve_default=False,
        ),
    ]
